
## Fixing the files for Mantel Local 

```{r}
library(tidyverse)
library(dplyr)
library(reshape2)
library(foreach)
getwd()
#Reading in Mantel Correlogram Results from Behavior Space Run

Mantel_localexp4<-readRDS("exp4_mantel_local.rds")
head(Mantel_localexp4)
View(Mantel_localexp4)

#Mantel_localexp3[c(418)] <- NULL  no need for this correction
#you had to turn it into a dataframe first after cleaning it up. Then you can turn the dataframe into a tibble


#this will clean up the data
Mantelstatsexp4<- foreach(i=seq_along(Mantel_localexp4)) %do% {   
  Mantel_localexp4[[i]]$mantel.res
}

names(Mantel_localexp4) <- c(1:30)


#it had to be renamed again
#names(Mantelstatsexp1) <- c(1:30)  

###you have to make it into a df first then take out the mantel r column
dfMantellocal<-as.data.frame(Mantelstatsexp4)
head(dfMantellocal)
Mantelstatsexp4<-dfMantellocal %>% 
  select(cols = contains("Mantel.cor")) %>% melt(cols=c("1":"30"), id.vars=NULL) %>%
  select(cols = "value") %>% dplyr::rename(Mantel.local = cols)

#pulling out the pvalue in case it is needed 
Pvalueexp4<-dfMantellocal %>%
   select(cols = contains("Pr.corrected.")) %>% melt(cols=c("1":"30"), id.vars=NULL) %>%
  select(cols = "value") %>% dplyr::rename(P.value = cols) 

#pulling out class index column 
Distanceexp4<-dfMantellocal %>%
   select(cols = contains("class.index")) %>% reshape2::melt(cols=c("1":"30"), id.vars=NULL) %>%
  select(cols = "value") %>% dplyr::rename(Class.Index = cols) 

#combining all 3 columns 
MantelLocalCorrexp4<-cbind(Mantelstatsexp4, Distanceexp4, Pvalueexp4)

```


```{r}
#reading in the parameter table from the Behavior Space Run
ParameterTableexp4<-read.csv("table_exp4Nursery149Mimic.csv")
#just making the name smaller. 
dfMantelLocalexp4<-ParameterTableexp4 
View(ParameterTableexp4)


```

```{r}
#this made replicates of the rows for the runs. So fifteen rows of Run 1, fifteen rows of Run 2 etc... 
#I did this so I can join the fiften new rows of the CorrColumnsNeeded file to the ParameterTableMimic file. Repeat rows 1 through XXX number of runs, 15 times, for all columns , ] 

Parametersexp4fixed<-dfMantelLocalexp4[rep(seq_len(nrow(dfMantelLocalexp4)), each = 15), ]   
Parametersexp4fixed
View(Parametersexp4fixed)
```

```{r}
#combine all columns for final 
MantelLocalFinalexp4<- cbind(MantelLocalCorrexp4, Parametersexp4fixed)  
write.csv(MantelLocalFinalexp4, "MantelLocalFinalexp4.csv")
View(MantelLocalFinalexp4)

```


```{r}
## Visualization

library(ggplot2)
#you have to graph it like a linear model if you have more than 2 variables. 
#ggplot needs for this column to be change to as.factor to graph it

#fixing before graphing
MantelLocalFinalexp4<-MantelLocalFinalexp4 %>% dplyr::rename(Nursery = Num.nursery)
MantelLocalFinalexp4$Nursery = as.factor(MantelLocalFinalexp4$Nursery)
#MantelLocalFinalexp4<-MantelLocalFinalexp4 %>% dplyr::rename(HT = Happy.type)

#graph
 ggplot(MantelLocalFinalexp4, aes(x = as.numeric(as.character(Class.Index)), y = Mantel.local, color = Nursery,
  shape= Nursery)) + 
  geom_point(alpha = 0.2) + geom_smooth(se = FALSE) + scale_x_continuous(limits = c(0,30), breaks = c(10,20,30)) + scale_y_continuous(limits = c(0,0.08), breaks = seq(0,0.08, by=0.02)) +
  geom_hline(yintercept = 0, linetype = 'longdash') + facet_grid(Neighbor.dist ~ Comparison.type, labeller = "label_both") +
  labs(x = "Yard Distance", y = "Mantel R", title = "Local Mantel R Over 30 Yards", subtitle = "Nurseries 1,4,9") + theme_bw()
```

